/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_helloworld_MyJNI */

#ifndef _Included_com_example_helloworld_MyJNI
#define _Included_com_example_helloworld_MyJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_helloworld_MyJNI
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_helloworld_MyJNI_getString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
